

export const product = [
    {
        id: 1,
        image: "images/camera.jpeg",
        title: "Digital Camera with Hd",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "electronics",
        price: 20000,
        discountPercentage: 7.17,
        rating: 4.94,
        stock: 5
    },
    {
        id: 2,
        image: "images/camera2.jpeg",
        title: "Digital Camera with Hd Quality",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "electronics",
        price: 40000,
        discountPercentage: 8.17,
        rating: 4,
        stock: 6,
    },
    {
        id: 3,
        image: "images/camera3.jpeg",
        title: "Digital Camera with Hd 3",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "electronics",
        price: 25000,
        discountPercentage: 10.17,
        rating: 3,
        stock: 6,
    },
    {
        id: 4,
        image: "images/coat.jpeg",
        title: "Mens Coat for looking awessome",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "clothes",
        price: 6000,
        discountPercentage: 2.17,
        rating: 2,
        stock: 8,
    },
    {
        id: 5,
        image: "images/wojeans.jpeg",
        title: "Jeans for all man and womens",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "clothes",
        price: 8000,
        discountPercentage: 7.17,
        rating: 6,
        stock: 8,
    },
    {
        id: 6,
        image: "images/women2 jeans.jpeg",
        title: "Mens Coat for looking awessome",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "clothes",
        price: 6000,
        discountPercentage: 2.17,
        rating: 2,
        stock: 8,
    },

    {
        id: 7,
        image: "images/laptop3.jpeg",
        title: "Awesome Laptop for Education",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "Electronics",
        price: 60000,
        discountPercentage: 7.17,
        rating: 5,
        stock: 2,
    },
    {
        id: 8,
        image: "images/mac.jpeg",
        title: "Macbook for Apple Lovers",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "Electronics",
        price: 70000,
        discountPercentage: 7.17,
        rating: 5,
        stock: 2,
    },
    {
        id: 9,
        image: "images/shoes.webp",
        title: "Good Footwear for Boys in range",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "footwear",
        price: 70000,
        discountPercentage: 7.17,
        rating: 5,
        stock: 2,
    },


 {
        id: 10,
        image: "images/veg.jpeg",
        title: "Vegatable for Resturant and hotel",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "veg",
        price: 1000,
        discountPercentage: 7.17,
        rating: 3,
        stock: 7,
    },

    {
        id: 11,
        image: "images/veg2.webp",
        title: "Vegatable for Resturant and hotel 2",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        category: "veg",
        price: 2000,
        discountPercentage: 7.17,
        rating: 3,
        stock: 7,
    },


    
]